name: othman
description: 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^1.3.0
  google_fonts: ^2.1.0
  quran: ^1.0.3
  stopper: ^1.0.1
  persistent_bottom_nav_bar: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/SuraNumber.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: Tajawal
    fonts:
      - asset: assets/fonts/Tajawal-Regular.ttf
        weight: 400
      - asset: assets/fonts/Tajawal-Medium.ttf
        weight: 500
      - asset: assets/fonts/Tajawal-Bold.ttf
        weight: 600
      - asset: assets/fonts/Tajawal-ExtraBold.ttf
        weight: 700
  - family: Quran
    fonts:
        - asset: assets/fonts/QuranFont.ttf
